# Generated by Django 5.0.4 on 2024-04-13 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0003_profile_follows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="follows",
        ),
    ]
