# Generated by Django 5.0.4 on 2024-04-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0005_profile_follows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="auth_user.profile"
            ),
        ),
    ]
