# Generated by Django 5.0.4 on 2024-04-18 01:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0008_alter_post_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
