# Generated by Django 5.0.4 on 2024-05-04 17:05

import auth_user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0009_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=auth_user.models.upload_to
            ),
        ),
    ]
